CREATE TABLE IF NOT EXISTS "musicbrainz_artist" ("gid" char(32) NOT NULL, "name" varchar(200) NOT NULL, "id" integer NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "musicbrainz_tag" ("gid" char(32) NOT NULL, "name" varchar(50) NOT NULL, "id" integer NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "musicbrainz_release_tag" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "musicbrainz_release_id" integer NOT NULL REFERENCES "musicbrainz_release" ("id") DEFERRABLE INITIALLY DEFERRED, "musicbrainz_tag_id" integer NOT NULL REFERENCES "musicbrainz_tag" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "musicbrainz_recording_artist" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "musicbrainz_recording_id" integer NOT NULL REFERENCES "musicbrainz_recording" ("id") DEFERRABLE INITIALLY DEFERRED, "musicbrainz_artist_id" integer NOT NULL REFERENCES "musicbrainz_artist" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "musicbrainz_recording_tag" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "musicbrainz_recording_id" integer NOT NULL REFERENCES "musicbrainz_recording" ("id") DEFERRABLE INITIALLY DEFERRED, "musicbrainz_tag_id" integer NOT NULL REFERENCES "musicbrainz_tag" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "musicbrainz_recording" ("id" integer NOT NULL PRIMARY KEY, "gid" char(32) NOT NULL, "name" varchar(200) NOT NULL, "release_id" integer NOT NULL REFERENCES "musicbrainz_release" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "musicbrainz_release" ("id" integer NOT NULL PRIMARY KEY, "gid" char(32) NOT NULL, "name" varchar(200) NOT NULL, "artist_credit" integer NOT NULL, "publishdate" smallint NOT NULL);
CREATE TABLE IF NOT EXISTS "musicbrainz_release_artist" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "musicbrainz_release_id" integer NOT NULL REFERENCES "musicbrainz_release" ("id") DEFERRABLE INITIALLY DEFERRED, "musicbrainz_artist_id" integer NOT NULL REFERENCES "musicbrainz_artist" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "musicbrainz_artist_tag" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "musicbrainz_artist_id" integer NOT NULL REFERENCES "musicbrainz_artist" ("id") DEFERRABLE INITIALLY DEFERRED, "musicbrainz_tag_id" integer NOT NULL REFERENCES "musicbrainz_tag" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "musicbrainz_release_tag_musicbrainz_release_id_36a06e90" ON "musicbrainz_release_tag" ("musicbrainz_release_id");
CREATE INDEX "musicbrainz_release_tag_musicbrainz_tag_id_7558fadb" ON "musicbrainz_release_tag" ("musicbrainz_tag_id");
CREATE UNIQUE INDEX "musicbrainz_recording_tag_musicbrainz_recording_id_musicbrainz_tag_id_3b8f808c_uniq" ON "musicbrainz_recording_tag" ("musicbrainz_recording_id", "musicbrainz_tag_id");
CREATE INDEX "musicbrainz_recording_tag_musicbrainz_recording_id_2c18ab1b" ON "musicbrainz_recording_tag" ("musicbrainz_recording_id");
CREATE INDEX "musicbrainz_recording_tag_musicbrainz_tag_id_82e5d367" ON "musicbrainz_recording_tag" ("musicbrainz_tag_id");
CREATE INDEX "musicbrainz_recording_release_id_aa87d3b3" ON "musicbrainz_recording" ("release_id");
CREATE UNIQUE INDEX "musicbrainz_release_artist_musicbrainz_release_id_musicbrainz_artist_id_bb67af71_uniq" ON "musicbrainz_release_artist" ("musicbrainz_release_id", "musicbrainz_artist_id");
CREATE INDEX "musicbrainz_release_artist_musicbrainz_release_id_839ff723" ON "musicbrainz_release_artist" ("musicbrainz_release_id");
CREATE INDEX "musicbrainz_release_artist_musicbrainz_artist_id_0f93ff4a" ON "musicbrainz_release_artist" ("musicbrainz_artist_id");
CREATE INDEX "musicbrainz_artist_tag_musicbrainz_artist_id_a28d53c6" ON "musicbrainz_artist_tag" ("musicbrainz_artist_id");
CREATE INDEX "musicbrainz_artist_tag_musicbrainz_tag_id_c2990417" ON "musicbrainz_artist_tag" ("musicbrainz_tag_id");
CREATE UNIQUE INDEX "musicbrainz_recording_artist_musicbrainz_recording_id_musicbrainz_artist_id_331637fc_uniq" ON "musicbrainz_recording_artist" ("musicbrainz_recording_id", "musicbrainz_artist_id");
CREATE INDEX "musicbrainz_recording_artist_musicbrainz_recording_id_de57d98d" ON "musicbrainz_recording_artist" ("musicbrainz_recording_id");
CREATE INDEX "musicbrainz_recording_artist_musicbrainz_artist_id_bd6dd7e4" ON "musicbrainz_recording_artist" ("musicbrainz_artist_id");
CREATE UNIQUE INDEX "musicbrainz_release_tag_musicbrainz_release_id_musicbrainz_tag_id_70b7224e_uniq" ON "musicbrainz_release_tag" ("musicbrainz_release_id", "musicbrainz_tag_id");
CREATE TABLE IF NOT EXISTS "musicbrainz_artist_credit_name" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "artist_credit" integer NOT NULL, "artist_id" integer NOT NULL);
CREATE INDEX "musicbrainz_artist_credit_name_artist_credit_36a06e90" ON "musicbrainz_artist_credit_name" ("artist_credit");
CREATE TABLE IF NOT EXISTS "musicbrainz_medium" ("id" integer NOT NULL PRIMARY KEY, "release" integer NOT NULL);
